# .github/workflows/ci.yml

name: Build, Test, and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t ./.python_packages/lib/site-packages

      - name: Add packages to PATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)/.python_packages/lib/site-packages" >> $GITHUB_ENV
          echo "$(pwd)/.python_packages/lib/site-packages/bin" >> $GITHUB_PATH
          
      - name: Run tests with pytest
        run: |
          pytest
      
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: .
          if-no-files-found: error

  deploy:
      runs-on: ubuntu-latest
      needs: build-and-test
      permissions:
        id-token: write #This is required for requesting the JWT
        contents: read #This is required for actions/checkout

      steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v4
          with:
            name: python-app
        
        - name: Login to Azure
          uses: azure/login@v2
          with:
            client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_26165423D99F4FC9822E086003E5C9D7 }}
            tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B5E1ED0AAF6D4BB6AB1A29FF7C75E3A3 }}
            subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8EE8583DD5304D958A515244D23D1B46 }}

        - name: 'Deploy to Azure Web App'
          uses: azure/webapps-deploy@v3
          id: deploy-to-webapp
          with:
            app-name: 'auto-prospector'
            package: '.'